import '../models/food_product.dart';

/// Тайёр овқат каталоги. Маҳсулотлар + категориялар. Кириллнинг сақланганлиги
/// учун `category` фильтри қиймати ҳам кирилл матнларида.
class FoodCatalog {
  FoodCatalog._();

  static const String allCategoryKey = 'Барчаси';

  static const List<String> categories = [
    allCategoryKey,
    'Асосий',
    'Товуқ',
    'Балиқ',
    'Шўрва',
    'Ичимликлар',
  ];

  static const List<FoodProduct> products = [
    FoodProduct(
        id: 1,
        name: 'Ош',
        emoji: '🍚',
        price: 45000,
        unit: 'кг',
        minQty: 0.5,
        step: 0.5,
        category: 'Асосий',
        desc: 'Тозалиги ва мазаси билан'),
    FoodProduct(
        id: 2,
        name: 'Товуқ табака',
        emoji: '🍗',
        price: 60000,
        unit: 'кг',
        minQty: 0.5,
        step: 0.5,
        category: 'Товуқ',
        desc: 'Тандирда босиб пишган'),
    FoodProduct(
        id: 3,
        name: 'Товуқ қовурдоқ',
        emoji: '🍳',
        price: 55000,
        unit: 'кг',
        minQty: 0.5,
        step: 0.5,
        category: 'Товуқ',
        desc: 'Зираворлар билан қовурилган'),
    FoodProduct(
        id: 4,
        name: 'Чўғда пишган товуқ',
        emoji: '🔥',
        price: 65000,
        unit: 'кг',
        minQty: 0.5,
        step: 0.5,
        category: 'Товуқ',
        desc: 'Кўмир устида'),
    FoodProduct(
        id: 5,
        name: 'Сарёғда қовурилган товуқ',
        emoji: '🧈',
        price: 70000,
        unit: 'кг',
        minQty: 0.5,
        step: 0.5,
        category: 'Товуқ',
        desc: 'Асл сарёғда'),
    FoodProduct(
        id: 6,
        name: 'Қовурилган балиқ',
        emoji: '🐟',
        price: 80000,
        unit: 'кг',
        minQty: 0.5,
        step: 0.5,
        category: 'Балиқ',
        desc: 'Тоза балиқ, зираворлар билан'),
    FoodProduct(
        id: 7,
        name: 'Кўмирда пишган балиқ',
        emoji: '🐠',
        price: 90000,
        unit: 'кг',
        minQty: 0.5,
        step: 0.5,
        category: 'Балиқ',
        desc: 'Кўмир ўтида'),
    FoodProduct(
        id: 8,
        name: 'Иликли шўрва',
        emoji: '🍲',
        price: 25000,
        unit: 'литр',
        minQty: 1.0,
        step: 0.5,
        category: 'Шўрва',
        desc: 'Иссиқ, тўйимли'),
    FoodProduct(
        id: 9,
        name: 'Мастава',
        emoji: '🥘',
        price: 22000,
        unit: 'литр',
        minQty: 1.0,
        step: 0.5,
        category: 'Шўрва',
        desc: 'Гуруч билан шўрва'),
    FoodProduct(
        id: 10,
        name: 'Димлама',
        emoji: '🫕',
        price: 50000,
        unit: 'кг',
        minQty: 0.5,
        step: 0.5,
        category: 'Асосий',
        desc: 'Сабзавотлар билан дамланган гўшт'),
    FoodProduct(
        id: 11,
        name: 'Қовурдоқ',
        emoji: '🥩',
        price: 75000,
        unit: 'кг',
        minQty: 0.5,
        step: 0.5,
        category: 'Асосий',
        desc: 'Думба ёғида қовурилган'),
    FoodProduct(
        id: 12,
        name: 'Шашлик',
        emoji: '🍢',
        price: 85000,
        unit: 'кг',
        minQty: 0.5,
        step: 0.5,
        category: 'Асосий',
        desc: 'Кўмирда пишган'),
    // ─── Ичимликлар (дона / шиша) — нархлар тахминий, админ вебдан ўзгартиринг
    FoodProduct(
        id: 13,
        name: 'Сув 0.5 л',
        emoji: '💧',
        price: 3000,
        unit: 'дона',
        minQty: 1,
        step: 1,
        category: 'Ичимликлар',
        desc: 'Ичимлик сув'),
    FoodProduct(
        id: 14,
        name: 'Сув 1.5 л',
        emoji: '💧',
        price: 6000,
        unit: 'дона',
        minQty: 1,
        step: 1,
        category: 'Ичимликлар',
        desc: 'Катта шиша'),
    FoodProduct(
        id: 15,
        name: 'Кола 1 л',
        emoji: '🥤',
        price: 10000,
        unit: 'дона',
        minQty: 1,
        step: 1,
        category: 'Ичимликлар',
        desc: 'Газли ичимлик'),
    FoodProduct(
        id: 16,
        name: 'Фанта 1 л',
        emoji: '🍊',
        price: 10000,
        unit: 'дона',
        minQty: 1,
        step: 1,
        category: 'Ичимликлар',
        desc: 'Апельсин мазаси'),
    FoodProduct(
        id: 17,
        name: 'Спрайт 1 л',
        emoji: '🍋',
        price: 10000,
        unit: 'дона',
        minQty: 1,
        step: 1,
        category: 'Ичимликлар',
        desc: 'Лимон-лайм'),
    FoodProduct(
        id: 18,
        name: 'Шарбат 1 л',
        emoji: '🧃',
        price: 12000,
        unit: 'дона',
        minQty: 1,
        step: 1,
        category: 'Ичимликлар',
        desc: 'Мева шарбати'),
    FoodProduct(
        id: 19,
        name: 'Айран 0.5 л',
        emoji: '🥛',
        price: 7000,
        unit: 'дона',
        minQty: 1,
        step: 1,
        category: 'Ичимликлар',
        desc: 'Совуқ айран'),
    FoodProduct(
        id: 20,
        name: 'Сут 1 л',
        emoji: '🥛',
        price: 14000,
        unit: 'дона',
        minQty: 1,
        step: 1,
        category: 'Ичимликлар',
        desc: 'Пастеризланган'),
    FoodProduct(
        id: 21,
        name: 'Чой иссиқ 0.5 л',
        emoji: '☕',
        price: 5000,
        unit: 'дона',
        minQty: 1,
        step: 1,
        category: 'Ичимликлар',
        desc: 'Тайёр шишада'),
    FoodProduct(
        id: 22,
        name: 'Компот 1 л',
        emoji: '🫙',
        price: 11000,
        unit: 'дона',
        minQty: 1,
        step: 1,
        category: 'Ичимликлар',
        desc: 'Уй компоти'),
  ];

  static FoodProduct byId(int id) =>
      products.firstWhere((p) => p.id == id);

  static List<FoodProduct> byCategory(String category) {
    if (category == allCategoryKey) return products;
    return products
        .where((p) => p.category == category)
        .toList(growable: false);
  }
}
